# Generated by Django 4.1.13 on 2024-08-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
