# Generated by Django 4.1.13 on 2024-08-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_language_remove_movie_language_movie_movie_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='starring_actors',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
