# Generated by Django 4.1.13 on 2024-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_bookedseats_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
