# Generated by Django 4.1.13 on 2024-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_seats_timing_theatre_movie_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtiming',
            field=models.ManyToManyField(related_name='movies_timings', to='booking_app.timing'),
        ),
    ]
