# Generated by Django 4.1.13 on 2024-08-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_movie_showtiming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='time',
        ),
        migrations.AddField(
            model_name='theatre',
            name='movie',
            field=models.ManyToManyField(related_name='theatres', to='booking_app.movie'),
        ),
    ]
