# Generated by Django 4.1.13 on 2024-08-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_rating_remove_movie_director_remove_movie_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='star_rating',
            field=models.ManyToManyField(related_name='movies', to='booking_app.starrating'),
        ),
    ]
