# Generated by Django 4.1.13 on 2024-08-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_remove_movie_theatre_remove_theatre_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='movie',
            new_name='title',
        ),
    ]
