# Generated by Django 4.1.13 on 2024-08-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_starrating_movie_star_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
    ]
