# Generated by Django 4.1.13 on 2024-08-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_rename_movie_theatre_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='title',
            new_name='movie',
        ),
    ]
