# Generated by Django 4.1.13 on 2024-08-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_rename_title_theatre_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='cinemas',
            field=models.ManyToManyField(related_name='theatre_locations', to='booking_app.theatre'),
        ),
    ]
