# Generated by Django 4.1.13 on 2024-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_rename_city_name_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='movie',
            name='time_length',
            field=models.CharField(default='2 hrs 50 mins', max_length=100),
        ),
    ]
