# Generated by Django 4.1.13 on 2024-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_remove_movie_location_location_cinemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(related_name='movie_genre', to='booking_app.movie'),
        ),
        migrations.AddField(
            model_name='language',
            name='movie',
            field=models.ManyToManyField(related_name='movie_language', to='booking_app.movie'),
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ManyToManyField(related_name='movie_rating', to='booking_app.movie'),
        ),
        migrations.AddField(
            model_name='starrating',
            name='movie',
            field=models.ManyToManyField(related_name='movie_star_rating', to='booking_app.movie'),
        ),
        migrations.AddField(
            model_name='timing',
            name='movie',
            field=models.ManyToManyField(related_name='movie_show_timings', to='booking_app.movie'),
        ),
    ]
