# Generated by Django 4.1.13 on 2024-08-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_remove_movie_movie_genre_remove_movie_movie_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='showtiming',
        ),
    ]
