# Generated by Django 4.1.13 on 2024-08-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_remove_movie_showtiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='genre',
            field=models.ManyToManyField(related_name='movies_genre', to='booking_app.genre'),
        ),
        migrations.AddField(
            model_name='theatre',
            name='language',
            field=models.ManyToManyField(related_name='movies_language', to='booking_app.language'),
        ),
        migrations.AddField(
            model_name='theatre',
            name='rating',
            field=models.ManyToManyField(related_name='movies_rating', to='booking_app.rating'),
        ),
        migrations.AddField(
            model_name='theatre',
            name='star_rating',
            field=models.ManyToManyField(related_name='movies_star_rating', to='booking_app.starrating'),
        ),
        migrations.AddField(
            model_name='theatre',
            name='timing',
            field=models.ManyToManyField(related_name='movies_star_rating', to='booking_app.timing'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='movie',
            field=models.ManyToManyField(related_name='theatre_movies', to='booking_app.movie'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='seat',
            field=models.ManyToManyField(related_name='theatre_seats', to='booking_app.seats'),
        ),
    ]
