# Generated by Django 4.1.13 on 2024-08-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0012_movie_genre_movie_language_movie_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='language',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='starrating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='timing',
            field=models.ManyToManyField(related_name='movies_timings', to='booking_app.timing'),
        ),
    ]
