# Generated by Django 4.1.13 on 2024-08-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0013_remove_genre_movie_remove_language_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='language',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='star_rating',
        ),
    ]
