# Generated by Django 4.1.13 on 2024-08-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0014_remove_theatre_genre_remove_theatre_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cinema',
            field=models.ManyToManyField(related_name='movie_theatres', to='booking_app.theatre'),
        ),
    ]
