# Generated by Django 4.1.13 on 2024-08-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0015_movie_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='movie',
        ),
    ]
