# Generated by Django 4.1.13 on 2024-08-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0016_remove_theatre_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='seat',
        ),
    ]
