# Generated by Django 4.1.13 on 2024-08-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0017_remove_timing_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='seat',
        ),
        migrations.AddField(
            model_name='movie',
            name='seat',
            field=models.ManyToManyField(related_name='theatre_seats', to='booking_app.seats'),
        ),
    ]
