# Generated by Django 4.1.13 on 2024-08-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0018_remove_theatre_seat_movie_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='cinemas',
            field=models.ManyToManyField(related_name='movie_cinemas', to='booking_app.location'),
        ),
    ]
