# Generated by Django 4.1.13 on 2024-08-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0019_theatre_cinemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='cinemas',
        ),
        migrations.AddField(
            model_name='theatre',
            name='location',
            field=models.ManyToManyField(related_name='movie_city', to='booking_app.location'),
        ),
    ]
