# Generated by Django 4.1.13 on 2024-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0021_seats_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='price',
            field=models.CharField(default=300, max_length=50),
        ),
    ]
